import ComtrollerCards from "./cards/controller_cards.js";
import ControllerFilter from "./filter/controller_filter.js";
import ControllerLikometr from "./likometr/controller_likometr.js";
import ControllerModal from "./modal/controller_modal.js";
import ControllerSearch from "./search/controller_search.js";
import ControllerSort from "./sort/controller_sort.js";
const controllerCards = new ComtrollerCards();
const controllerSort = new ControllerSort();
const controllerFilter = new ControllerFilter();
const controllerSearch = new ControllerSearch();
const controllerModal = new ControllerModal();
// const controllerLikometr = new ControllerLikometr();
